language: node_js
cache: yarn
matrix:
  fast_finish: true
  include:
    - node_js: node
      env: WEBPACK_VERSION=3 BABEL_LOADER=7
    - node_js: 8
      env: WEBPACK_VERSION=3 BABEL_LOADER=7
    - node_js: 6
      env: WEBPACK_VERSION=3 BABEL_LOADER=7
    - node_js: 6
      env: WEBPACK_VERSION=2 BABEL_LOADER=7
before_script:
  - npm install webpack@$WEBPACK_VERSION babel-loader@$BABEL_LOADER
script:
  - npm run build
  - npm test
